name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -race $(go list ./... | grep -v /vendor/)

    - name: Format
      run: |
        if [ -n "$(gofmt -l $(go list -f {{.Dir}} ./...| grep -v /vendor/))" ]; then
          echo "Go code is not formatted:"
          gofmt -d $(go list -f {{.Dir}} ./...| grep -v /vendor/)
          exit 1
        fi

    - name: Vet
      run: go vet $(go list ./... | grep -v /vendor/)

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -race $(go list ./... | grep -v /vendor/)

    - name: Vet
      run: go vet $(go list ./... | grep -v /vendor/)
